data_dir: data/dbase
do_sample: true
embeddings_model: all-MiniLM-L6-v2
hf_api_key: ${}
llm_model: meta-llama/Llama-3.1-8B-Instruct
max_tokens: 500
nlp_model: en_core_web_trf
repetition_penalty: 1.1
similarity_threshold: 0.65
temperature: 0.55
